### ISSUE TITLE
Spaces and Special Characters in FIlenames

### ISSUE THREAD

**Issue by Joe91** [peterus/ESP-FTP-Server-Lib#41]
First of all: Thanks a lot! It works really super stable and is very fast in the upload compared to other solutions.

The issue I have:
If the files contain spaces (or other non-standard characeters) the file won't be created on the filesystem with this name. 
Changing the charset to force UTF8 or something else does not help.
With spaces it only takes the first part to the first space (file completely fine).
With special characters (like "ö" or "ß" or so) it does not work at all.
In the other direction (Download from FTP server) the same thing, but It fails in both cases.

Also creating folders with spaces has the same issue (will only create the part before the first space).

Is there a fix or workaround already available?

I'm using the ES32 with the SDMMCFS.

**Comment by Joe91** [comment]
Update:
the reason for the spaces is https://github.com/peterus/ESP-FTP-Server-Lib/blob/master/src/FTPConnection.cpp#L74
when I replace this line with this, the spaces in folders and filenames work again:
`_LineSplited = {_Line.substring(0, index_separator), _Line.substring(index_separator + 1, _Line.length())};`

**Comment by peterus** [comment]
@Joe91 thank you for taking a look into it!
can you create a merge request? than I will merge your change 😉

**Comment by Joe91** [comment]
Yeah, of course.
I want to check some things first. 
Also got UTF-8 support working but I want to check if there are some commands, that might need some special handling.
Will create a PR this evening if everything works fine :-)

**Comment by peterus** [comment]
@Joe91 thanks for your PR, it is already merged ;) new version will come soon!
